joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min: 0.2
      linear_forward_max: 7.0
      Linear_backward_min: 0.2
      Linear_backward_max: 0.7
      angular_min: 0.7
      angular_max: 5.0
      steps: 3